client
dev tun
proto udp
remote 192.168.191.160 1194   # <-- заменить на IP сервера или домен
resolv-retry infinite
nobind
persist-key
persist-tun

connect-retry 3
connect-retry-max 5

remote-cert-tls server
cipher AES-256-CBC
auth SHA256
key-direction 1
verb 3

# Вставляем сертификаты и ключи inline
<ca>
{CA_CERT}
</ca>

<cert>
{CLIENT_CERT}
</cert>

<key>
{CLIENT_KEY}
</key>

<tls-auth>
{TLS_KEY}
</tls-auth>
